# Generated by Django 3.2.25 on 2024-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=32, verbose_name='Почта')),
                ('password', models.CharField(max_length=64, verbose_name='Пароль')),
                ('textarea', models.CharField(max_length=5000, verbose_name='Текстовое окно')),
            ],
        ),
    ]
