# Generated by Django 3.2.25 on 2024-04-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textarea', models.CharField(max_length=5000, verbose_name='Текстовое окно')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='textarea',
        ),
    ]
