# Generated by Django 3.2.25 on 2024-04-17 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0002_auto_20240410_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=128, verbose_name='Содержание')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Matrix.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
